(()=>{
  const pages=new Map();let key=null,current=null,active=null,color='#172444',size=3,eraser=false,expanded=false,mode='pen';
  const launch=document.createElement('button');launch.className='scratch-launch btn primary';launch.textContent='✎ กระดาษทด';launch.hidden=true;launch.setAttribute('aria-controls','scratch-panel');launch.setAttribute('aria-expanded','false');
  const panel=document.createElement('section');panel.id='scratch-panel';panel.className='scratch-panel';panel.hidden=true;panel.setAttribute('aria-label','กระดาษทดเลข');
  panel.innerHTML=`<div class="scratch-heading"><button class="btn scratch-expand" id="scratch-expand" aria-label="ขยายกระดาษทดเต็มจอ" aria-pressed="false">⛶ ขยาย</button><div class="scratch-title"><strong>กระดาษทด</strong><div id="scratch-label" class="muted"></div></div><button class="btn" id="scratch-close" aria-label="ปิดกระดาษทด">ปิด ×</button></div><div class="scratch-tools" role="group" aria-label="เครื่องมือเขียน"><button class="btn" id="scratch-pen" aria-pressed="true">ปากกา</button><button class="btn" id="scratch-pan" aria-pressed="false">✋ เลื่อนกระดาษ</button><button class="btn" id="scratch-zoom-out" aria-label="ย่อกระดาษทด">−</button><output id="scratch-scale" aria-label="ระดับซูมกระดาษทด">100%</output><button class="btn" id="scratch-zoom-in" aria-label="ขยายกระดาษทด">＋</button><button class="btn" id="scratch-origin">กลับจุดเริ่มต้น</button><button class="btn" id="scratch-eraser" aria-pressed="false">ยางลบ</button><label>หมึก <input id="scratch-color" type="color" value="#172444" aria-label="สีหมึกปากกา"></label><label>ขนาด <select id="scratch-size" aria-label="ขนาดหัวปากกา"><option value="2">เล็ก</option><option value="3" selected>กลาง</option><option value="6">ใหญ่</option></select></label><button class="btn" id="scratch-undo" aria-label="ย้อนกลับการเขียน">↶ ย้อนกลับ</button><button class="btn" id="scratch-redo" aria-label="ทำซ้ำการเขียน">↷ ทำซ้ำ</button><button class="btn" id="scratch-clear">ล้างหน้านี้</button></div><p class="scratch-hint">สองนิ้วเลื่อน / บีบเพื่อซูม • หรือเลือก ✋ เลื่อนกระดาษ<br>บันทึกรอยเขียนอัตโนมัติในเครื่องนี้</p><div class="scratch-scroll"><canvas id="scratch-canvas" width="900" height="600" tabindex="0" aria-label="พื้นที่เขียนทดเลขด้วยเมาส์ นิ้ว หรือปากกา"></canvas></div>`;
  document.body.append(launch,panel);
  const $=id=>panel.querySelector('#scratch-'+id),canvas=$('canvas'),ctx=canvas.getContext('2d'),pointers=new Map();
  let gesture=false,panLast=null,pinchLast=null,saveTimer=null,frame=null,cssWidth=900,cssHeight=600,dpr=1;
  const local=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
  const world=p=>({x:(p.x-current.camera.x)/current.camera.z,y:(p.y-current.camera.y)/current.camera.z});
  function tools(){if(current)$('scale').textContent=Math.round(current.camera.z*100)+'%';for(const id of ['pen','eraser','pan'])$(id).setAttribute('aria-pressed',String(mode===id));$('undo').disabled=!current?.strokes.length;$('redo').disabled=!current?.redo.length;$('clear').disabled=!current?.strokes.length;canvas.style.cursor=mode==='pan'?'grab':mode==='eraser'?'cell':'crosshair';}
  function draw(stroke){ctx.globalCompositeOperation=stroke.erase?'destination-out':'source-over';ctx.strokeStyle=stroke.color;ctx.fillStyle=stroke.color;ctx.lineWidth=stroke.width;ctx.lineCap='round';ctx.lineJoin='round';const pts=stroke.points;if(pts.length===1){ctx.beginPath();ctx.arc(pts[0].x,pts[0].y,stroke.width/2,0,Math.PI*2);ctx.fill();}else{ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();}ctx.globalCompositeOperation='source-over';}
  function paint(){frame=null;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);if(!current)return;const c=current.camera;ctx.setTransform(dpr*c.z,0,0,dpr*c.z,c.x*dpr,c.y*dpr);for(const stroke of current.strokes){const b=stroke.bounds;if(b&&((b.maxX*c.z+c.x)<-stroke.width*c.z||(b.minX*c.z+c.x)>cssWidth+stroke.width*c.z||(b.maxY*c.z+c.y)<-stroke.width*c.z||(b.minY*c.z+c.y)>cssHeight+stroke.width*c.z))continue;draw(stroke);}if(active)draw(active.stroke);canvas.style.backgroundSize=`${24*c.z}px ${24*c.z}px`;canvas.style.backgroundPosition=`${c.x}px ${c.y}px`;tools();}
  function schedule(){if(frame===null)frame=requestAnimationFrame(paint);}
  function resize(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;cssWidth=r.width;cssHeight=r.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(cssWidth*dpr);canvas.height=Math.round(cssHeight*dpr);paint();}
  function finish(){if(active){current.strokes.push(active.stroke);current.redo=[];active=null;savePage();}tools();}
  function resetPointers(){finish();const ids=[...pointers.keys()];pointers.clear();gesture=false;panLast=null;pinchLast=null;savePage();for(const id of ids)if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id);}
  function setExpanded(value){resetPointers();expanded=value;panel.classList[value?'add':'remove']('scratch-expanded');document.body.classList[value?'add':'remove']('scratch-fullscreen');$('expand').textContent=value?'⛶ ย่อกลับ':'⛶ ขยาย';$('expand').setAttribute('aria-label',value?'ย่อกระดาษทดกลับขนาดเดิม':'ขยายกระดาษทดเต็มจอ');$('expand').setAttribute('aria-pressed',String(value));requestAnimationFrame(resize);}
  function close(){resetPointers();setExpanded(false);panel.hidden=true;launch.setAttribute('aria-expanded','false');document.body.classList.remove('scratch-open');}
  launch.onclick=()=>{if(panel.hidden){panel.hidden=false;launch.setAttribute('aria-expanded','true');document.body.classList.add('scratch-open');resize();$('close').focus();}else close();};
  $('expand').onclick=()=>setExpanded(!expanded);$('close').onclick=()=>{close();launch.focus();};
  for(const id of ['pen','eraser','pan'])$(id).onclick=()=>{resetPointers();mode=id;tools();};
  $('origin').onclick=()=>{resetPointers();current.camera={x:0,y:0,z:1};paint();savePage();};
  $('color').oninput=e=>{resetPointers();color=e.target.value;mode='pen';tools();};$('size').onchange=e=>{finish();size=Number(e.target.value);};
  $('undo').onclick=()=>{resetPointers();if(current.strokes.length)current.redo.push(current.strokes.pop());paint();savePage();};$('redo').onclick=()=>{resetPointers();if(current.redo.length)current.strokes.push(current.redo.pop());paint();savePage();};
  $('clear').onclick=()=>{resetPointers();if(!current.strokes.length)return;const dialog=document.createElement('dialog');dialog.innerHTML='<h2>ล้างกระดาษทดข้อนี้?</h2><p>ลบรอยเขียนทั้งหมดของข้อนี้ รวมส่วนที่เลื่อนออกนอกจอ</p><div class="row"><button class="btn" data-cancel>ยกเลิก</button><button class="btn primary" data-clear>ล้างกระดาษ</button></div>';const page=current;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-clear]').onclick=()=>{page.strokes=[];page.redo=[];page.camera={x:0,y:0,z:1};paint();savePage();dialog.close();};dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();};
  function center(){const list=[...pointers.values()];return {x:list.reduce((s,p)=>s+p.x,0)/list.length,y:list.reduce((s,p)=>s+p.y,0)/list.length};}
  canvas.addEventListener('pointerdown',e=>{if(!current||(e.pointerType==='mouse'&&![0,1].includes(e.button)))return;if([...pointers.values()].some(p=>p.type==='pen')&&e.pointerType==='touch')return;e.preventDefault();const p=local(e);pointers.set(e.pointerId,{...p,type:e.pointerType});canvas.setPointerCapture(e.pointerId);if(pointers.size>1){active=null;gesture=true;panLast=center();pinchLast=distance();schedule();return;}if(mode==='pan'||e.button===1){gesture=true;panLast=p;return;}const w=world(p);active={id:e.pointerId,stroke:{erase:mode==='eraser',color,width:(mode==='eraser'?24:size)/current.camera.z,points:[w],bounds:{minX:w.x,maxX:w.x,minY:w.y,maxY:w.y}}};schedule();});
  canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!current)return;e.preventDefault();pointers.set(e.pointerId,{...local(e),type:e.pointerType});if(gesture){const c=center(),dist=distance();if(panLast){const before=world(panLast),z=clampScale(current.camera.z*(dist&&pinchLast?dist/pinchLast:1));current.camera={x:c.x-before.x*z,y:c.y-before.y*z,z};}panLast=c;pinchLast=dist;schedule();return;}if(active?.id!==e.pointerId)return;const list=e.getCoalescedEvents?.()||[e];for(const sample of list.length?list:[e]){const p=world(local(sample)),b=active.stroke.bounds;active.stroke.points.push(p);b.minX=Math.min(b.minX,p.x);b.maxX=Math.max(b.maxX,p.x);b.minY=Math.min(b.minY,p.y);b.maxY=Math.max(b.maxY,p.y);}schedule();});
  function release(e){if(!pointers.has(e.pointerId))return;if(active?.id===e.pointerId)finish();pointers.delete(e.pointerId);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);panLast=pointers.size?center():null;pinchLast=distance();if(!pointers.size)gesture=false;savePage();schedule();}
  for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,release);
  canvas.addEventListener('wheel',e=>{if(!current||e.ctrlKey)return;e.preventDefault();finish();const unit=e.deltaMode===1?16:e.deltaMode===2?cssHeight:1;current.camera.x-=(e.shiftKey&&!e.deltaX?e.deltaY:e.deltaX)*unit;current.camera.y-=(e.shiftKey&&!e.deltaX?0:e.deltaY)*unit;queueSave();schedule();},{passive:false});
  canvas.addEventListener('keydown',e=>{if(!current)return;const d={ArrowLeft:[80,0],ArrowRight:[-80,0],ArrowUp:[0,80],ArrowDown:[0,-80]}[e.key];if(d){e.preventDefault();finish();current.camera.x+=d[0];current.camera.y+=d[1];savePage();schedule();}});
  panel.addEventListener('keydown',e=>{if(e.key==='Escape'){if(expanded){setExpanded(false);$('expand').focus();}else{close();launch.focus();}}});
  window.addEventListener('blur',resetPointers);new ResizeObserver(resize).observe(canvas);
  window.Scratch={setQuestion(subject,n,title){resetPointers();key=subject+':'+n;if(!pages.has(key)){const saved=window.QuizStore?.get('scratch-'+key,null);pages.set(key,validPage(saved)?saved:{strokes:[],redo:[],camera:{x:0,y:0,z:1}});}current=pages.get(key);$('label').textContent=title+' · ข้อ '+n;launch.hidden=false;resize();},hide(){close();launch.hidden=true;},hasNotes(){return [...pages.values()].some(p=>p.strokes.length>0);}};

  function validPage(p){return p&&Array.isArray(p.strokes)&&Array.isArray(p.redo)&&p.camera&&['x','y','z'].every(k=>Number.isFinite(p.camera[k]))&&p.camera.z>=.2&&p.camera.z<=5&&[...p.strokes,...p.redo].every(s=>Number.isFinite(s.width)&&Array.isArray(s.points)&&s.points.length&&s.points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));}
  function savePage(){if(current&&key)window.QuizStore?.set('scratch-'+key,current);}
  function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(savePage,200);}
  function distance(){const ps=[...pointers.values()];return ps.length>=2?Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y):null;}
  function clampScale(z){return Math.max(.2,Math.min(5,z));}
  function zoomBy(ratio){resetPointers();const center={x:cssWidth/2,y:cssHeight/2},p=world(center),z=clampScale(current.camera.z*ratio);current.camera={x:center.x-p.x*z,y:center.y-p.y*z,z};paint();savePage();}
  $('zoom-in').onclick=()=>zoomBy(1.25);$('zoom-out').onclick=()=>zoomBy(.8);
  window.addEventListener('pagehide',()=>{resetPointers();savePage();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){resetPointers();savePage();}});
  window.addEventListener('beforeunload',e=>{resetPointers();savePage();if(window.QuizStore?.failed()){e.preventDefault();e.returnValue='';}});
})();
